"""
8. Report Generation Agent

Compiles every upstream agent's output into a single readable markdown
report. This is the final node in the pipeline -- pure formatting, no LLM
call needed.
"""

from datetime import datetime
from src.state import PipelineState


def _fmt_list(items, empty="None"):
    """Bulleted list, one item per line -- use for standalone list sections."""
    if not items:
        return empty
    return "\n".join(f"- {item}" for item in items)


def _fmt_inline(items, empty="None"):
    """Comma-joined string -- use when the list follows a 'Label: ' prefix on the same line."""
    if not items:
        return empty
    return ", ".join(str(item) for item in items)


    
def run(state: PipelineState) -> dict:
    profile = state.get("patient_profile", {})
    entities = state.get("extracted_entities", {})
    risk = state.get("risk_result", {})
    evidence = state.get("retrieved_evidence", [])
    drug_safety = state.get("drug_safety_result", {})
    verification = state.get("guideline_verification", {})
    reasoning = state.get("clinical_reasoning", {})
    assessment = reasoning.get("assessment", "n/a")

    if assessment == "parse_error: could not parse model output as JSON":
     assessment = "Unable to generate a grounded clinical summary."

    evidence_section = "\n\n".join(
        f"**{e['source']}** (relevance {e['score']})\n> {e['snippet']}" for e in evidence
    ) or "No relevant evidence retrieved."

    interactions = drug_safety.get("interactions", [])
    interactions_section = "\n".join(
        f"- **{i['drug_a']} + {i['drug_b']}** ({i['severity']} severity): {i['description']}"
        for i in interactions
    ) or "No interaction flags found."

    report = f"""# Clinical AI Pipeline Report

> ⚠️ **DISCLAIMER: This report is generated by a demo software project for
> educational/portfolio purposes only. It uses synthetic data and a toy ML
> model. It must never be used for real clinical decision-making.**

**Generated:** {datetime.now().isoformat(timespec='seconds')}
**Patient:** {profile.get('name')} (ID: {profile.get('patient_id')})
**Age / Sex:** {profile.get('age')} / {profile.get('sex')}

---

## 1. Patient Profile
- Comorbidities: {_fmt_inline(profile.get('comorbidities'))}
- Smoker: {profile.get('smoker')}
- Current medications: {_fmt_inline(profile.get('current_medications'))}

## 2. Extracted Clinical Entities (NLP)
- Symptoms: {_fmt_inline(entities.get('symptoms'))}
- Mentioned conditions: {_fmt_inline(entities.get('mentioned_conditions'))}
- Mentioned medications: {_fmt_inline(entities.get('mentioned_medications'))}
- Notable flags: {_fmt_inline(entities.get('notable_flags'))}

## 3. Risk Prediction (ML)
- **Risk category:** {risk.get('risk_category', 'n/a').upper()}
- **Risk score:** {risk.get('risk_score', 'n/a')}
- Top contributing factors: {_fmt_inline(risk.get('top_factors'))}

## 4. Retrieved Evidence (RAG)
{evidence_section}

## 5. Drug Safety Check
{interactions_section}

## 6. Guideline Verification
- Aligned with retrieved evidence: {verification.get('aligned', 'n/a')}
- Notes: {verification.get('notes', 'n/a')}
- Citations: {_fmt_inline(verification.get('citations'))}

## 7. Clinical Reasoning Summary
- **Priority:** {reasoning.get('priority', 'n/a').upper()}
- Assessment: {assessment}
- Recommendations:
{_fmt_list(reasoning.get('recommendations'))}

---

## Pipeline Execution Trace
{_fmt_list(state.get('trace'))}
"""

    trace = ["[Report Generation Agent] Compiled final markdown report."]

    return {"final_report": report, "trace": trace}
